Repository ssi-dk/aedseo, pull requests merged in 2025-01, with the labels that each got.

#52 Changes to lnorm method
  R/fit_quantiles.R
  tests/testthat/test-fit_quantiles.R
Labels: bug

#53 Fixing error if current season does not surpass disease_threshold
  R/seasonal_burden_levels.R
  tests/testthat/test-seasonal_burden_levels.R
Labels: bug

#51 Fixing small issues
  CRAN-SUBMISSION
  DESCRIPTION
  NAMESPACE
  R/0_documentation.R
  R/autoplot.R
  R/combined_seasonal_output.R
  R/fit_quantiles.R
  R/predict.R
  R/seasonal_burden_levels.R
  R/seasonal_onset.R
  R/summary.R
  R/utils-pipe.R
  man/combined_seasonal_output.Rd
  man/fit_quantiles.Rd
  man/pipe.Rd
  man/seasonal_burden_levels.Rd
  man/seasonal_onset.Rd
  tests/testthat/test-combined_seasonal_output.R
  tests/testthat/test-fit_quantiles.R
  tests/testthat/test-seasonal_burden_levels.R
  tests/testthat/test-seasonal_onset.R
  tests/testthat/test-summary.R
Labels: refactor

#54 Fixing season in seasonal_burden_levels
  R/combined_seasonal_output.R
  R/seasonal_burden_levels.R
  R/seasonal_onset.R
  man/seasonal_onset.Rd
  tests/testthat/test-seasonal_burden_levels.R
Labels: bug

#55 Adding authors
  DESCRIPTION
  man/aedseo-package.Rd
Labels: documentation

#56 Simulation function for the package
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/1_utils.R
  R/autoplot.R
  R/generate_seasonal_data.R
  R/plot.R
  R/summary.R
  _pkgdown.yml
  man/aedseo-package.Rd
  man/autoplot.Rd
  man/generate_seasonal_data.Rd
  tests/testthat/test-combined_seasonal_output.R
  tests/testthat/test-fit_growth_rate.R
  tests/testthat/test-fit_quantiles.R
  tests/testthat/test-generate_seasonal_data.R
  tests/testthat/test-predict.R
  tests/testthat/test-seasonal_burden_levels.R
  tests/testthat/test-seasonal_onset.R
  tests/testthat/test-summary.R
  tests/testthat/test-to_time_series.R
  vignettes/aedseo.Rmd
  vignettes/generate_seasonal_wave.Rmd
Labels: documentation, enhancement

#57 Edit introduction vignette
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/0_documentation.R
  R/1_utils.R
  R/autoplot.R
  R/combined_seasonal_output.R
  R/generate_seasonal_data.R
  R/plot.R
  R/to_time_series.R
  README.md
  man/autoplot.Rd
  man/generate_seasonal_data.Rd
  man/plot.Rd
  man/to_time_series.Rd
  vignettes/aedseo.Rmd
  vignettes/burden_levels.Rmd
  vignettes/generate_seasonal_wave.Rmd
  vignettes/seasonal_onset.Rmd
Labels: documentation, refactor

#58 Add burden level vignette
  .github/workflows/pkgdown.yaml
  .github/workflows/test-coverage.yaml
  DESCRIPTION
  NEWS.md
  R/seasonal_burden_levels.R
  man/combined_seasonal_output.Rd
  man/seasonal_burden_levels.Rd
  vignettes/aedseo.Rmd
  vignettes/burden_levels.Rmd
  vignettes/generate_seasonal_wave.Rmd
Labels: documentation

#59 Vignette_harmonization
  R/generate_seasonal_data.R
  R/seasonal_burden_levels.R
  man/generate_seasonal_data.Rd
  tests/testthat/test-generate_seasonal_data.R
  tests/testthat/test-seasonal_burden_levels.R
  vignettes/aedseo.Rmd
  vignettes/burden_levels.Rmd
  vignettes/generate_seasonal_wave.Rmd
  vignettes/seasonal_onset.Rmd
Labels: documentation
